spring:
  application:
    name: spring-microservices-greeting

server:
  port: ${PORT:8081}
  servlet:
    context-path: /api/greeting

management:
  endpoints:
    web:
      exposure:
        include: "*"
