spring:
  application:
    name: spring-microservices-echo


server:
  port: ${PORT:8083}
  servlet:
    context-path: /api/echo

management:
  endpoints:
    web:
      exposure:
        include: "*"
